export const ARTIST_LIST_REQUEST = 'ARTIST_LIST_REQUEST';
export const ARTIST_LIST_SUCCESS = 'ARTIST_LIST_SUCCESS';
export const ARTIST_LIST_FAILURE = 'ARTIST_LIST_FAILURE';

export const ARTIST_REQUEST = 'ARTIST_REQUEST';
export const ARTIST_SUCCESS = 'ARTIST_SUCCESS';
export const ARTIST_FAILURE = 'ARTIST_FAILURE';

export const ADD_ARTIST_SUCCESS =  'ADD_ARTIST_SUCCESS';
export const ADD_ARTIST_FAILURE = 'ADD_ARTIST_FAILURE';

export const ALBUM_LIST_REQUEST = 'ALBUM_LIST_REQUEST';
export const ALBUM_LIST_SUCCESS = 'ALBUM_LIST_SUCCESS';
export const ALBUM_LIST_FAILURE = 'ALBUM_LIST_FAILURE';

export const ALL_AlBUM_SUCCESS = 'ALL_ALBUM_SUCCESS';
export const ALL_ALBUM_FAILURE = 'ALL_ALBUM_FAILURE';

export const ADD_ALBUM_SUCCESS =  'ADD_ALBUM_SUCCESS';
export const ADD_ALBUM_FAILURE = 'ADD_ALBUM_FAILURE';

export const TRACK_LIST_REQUEST = 'TRACK_LIST_REQUEST';
export const TRACK_LIST_SUCCESS = 'TRACK_LIST_SUCCESS';
export const TRACK_LIST_FAILURE = 'TRACK_LIST_FAILURE';

export const ALL_TRACK_SUCCESS = 'ALL_TRACK_SUCCESS';
export const ALL_TRACK_FAILURE = 'ALL_TRACK_FAILURE';

export const ADD_TRACK_SUCCESS =  'ADD_TRACK_SUCCESS';
export const ADD_TRACK_FAILURE = 'ADD_TRACK_FAILURE';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const POST_TRACK_HISTORY_SUCCESS = 'POST_TRACK_HISTORY_SUCCESS';
export const POST_TRACK_HISTORY_FAILURE = 'POST_TRACK_HISTORY_FAILURE';

export const TRACK_HISTORY_SUCCESS = 'TRACK_HISTORY_SUCCESS';
export const TRACK_HISTORY_FAILURE = 'TRACK_HISTORY_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const DELETE_ARTIST = 'DELETE_ARTIST';

export const DELETE_ALBUM = 'DELETE_ALBUM';

export const DELETE_TRACK = 'DELETE_TRACK';

export const PUBLISH_ARTIST_SUCCESS = 'PUBLISH_ARTIST_SUCCESS';

export const PUBLISH_ALBUM_SUCCESS = 'PUBLISH_ALBUM_SUCCESS';

export const PUBLISH_TRACK_SUCCESS = 'PUBLISH_TRACK_SUCCESS';



